// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Mahno9/GoMicroservicesCourse/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: c, uuid
func (_m *PartRepository) GetPart(c context.Context, uuid string) (*model.Part, error) {
	ret := _m.Called(c, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(c, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(c, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - c context.Context
//   - uuid string
func (_e *PartRepository_Expecter) GetPart(c interface{}, uuid interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", c, uuid)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(c context.Context, uuid string)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(_a0 *model.Part, _a1 error) *PartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// InitWithDummy provides a mock function with no fields
func (_m *PartRepository) InitWithDummy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitWithDummy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartRepository_InitWithDummy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitWithDummy'
type PartRepository_InitWithDummy_Call struct {
	*mock.Call
}

// InitWithDummy is a helper method to define mock.On call
func (_e *PartRepository_Expecter) InitWithDummy() *PartRepository_InitWithDummy_Call {
	return &PartRepository_InitWithDummy_Call{Call: _e.mock.On("InitWithDummy")}
}

func (_c *PartRepository_InitWithDummy_Call) Run(run func()) *PartRepository_InitWithDummy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PartRepository_InitWithDummy_Call) Return(_a0 error) *PartRepository_InitWithDummy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartRepository_InitWithDummy_Call) RunAndReturn(run func() error) *PartRepository_InitWithDummy_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: c, filter
func (_m *PartRepository) ListParts(c context.Context, filter *model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(c, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(c, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = rf(c, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PartsFilter) error); ok {
		r1 = rf(c, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - c context.Context
//   - filter *model.PartsFilter
func (_e *PartRepository_Expecter) ListParts(c interface{}, filter interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", c, filter)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(c context.Context, filter *model.PartsFilter)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PartsFilter))
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *PartRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(context.Context, *model.PartsFilter) ([]*model.Part, error)) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
