// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MongoCursor is an autogenerated mock type for the MongoCursor type
type MongoCursor struct {
	mock.Mock
}

type MongoCursor_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoCursor) EXPECT() *MongoCursor_Expecter {
	return &MongoCursor_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx, results
func (_m *MongoCursor) All(ctx context.Context, results interface{}) error {
	ret := _m.Called(ctx, results)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, results)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MongoCursor_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - results interface{}
func (_e *MongoCursor_Expecter) All(ctx interface{}, results interface{}) *MongoCursor_All_Call {
	return &MongoCursor_All_Call{Call: _e.mock.On("All", ctx, results)}
}

func (_c *MongoCursor_All_Call) Run(run func(ctx context.Context, results interface{})) *MongoCursor_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MongoCursor_All_Call) Return(_a0 error) *MongoCursor_All_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_All_Call) RunAndReturn(run func(context.Context, interface{}) error) *MongoCursor_All_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *MongoCursor) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoCursor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MongoCursor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MongoCursor_Expecter) Close(ctx interface{}) *MongoCursor_Close_Call {
	return &MongoCursor_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MongoCursor_Close_Call) Run(run func(ctx context.Context)) *MongoCursor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MongoCursor_Close_Call) Return(_a0 error) *MongoCursor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCursor_Close_Call) RunAndReturn(run func(context.Context) error) *MongoCursor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoCursor creates a new instance of MongoCursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoCursor {
	mock := &MongoCursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
