// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MongoIndexView is an autogenerated mock type for the MongoIndexView type
type MongoIndexView struct {
	mock.Mock
}

type MongoIndexView_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoIndexView) EXPECT() *MongoIndexView_Expecter {
	return &MongoIndexView_Expecter{mock: &_m.Mock}
}

// CreateOne provides a mock function with given fields: ctx, indexModel, opts
func (_m *MongoIndexView) CreateOne(ctx context.Context, indexModel mongo.IndexModel, opts ...*options.CreateIndexesOptions) (string, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, indexModel)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateOne")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mongo.IndexModel, ...*options.CreateIndexesOptions) (string, error)); ok {
		return rf(ctx, indexModel, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mongo.IndexModel, ...*options.CreateIndexesOptions) string); ok {
		r0 = rf(ctx, indexModel, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, mongo.IndexModel, ...*options.CreateIndexesOptions) error); ok {
		r1 = rf(ctx, indexModel, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoIndexView_CreateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOne'
type MongoIndexView_CreateOne_Call struct {
	*mock.Call
}

// CreateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - indexModel mongo.IndexModel
//   - opts ...*options.CreateIndexesOptions
func (_e *MongoIndexView_Expecter) CreateOne(ctx interface{}, indexModel interface{}, opts ...interface{}) *MongoIndexView_CreateOne_Call {
	return &MongoIndexView_CreateOne_Call{Call: _e.mock.On("CreateOne",
		append([]interface{}{ctx, indexModel}, opts...)...)}
}

func (_c *MongoIndexView_CreateOne_Call) Run(run func(ctx context.Context, indexModel mongo.IndexModel, opts ...*options.CreateIndexesOptions)) *MongoIndexView_CreateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.CreateIndexesOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.CreateIndexesOptions)
			}
		}
		run(args[0].(context.Context), args[1].(mongo.IndexModel), variadicArgs...)
	})
	return _c
}

func (_c *MongoIndexView_CreateOne_Call) Return(_a0 string, _a1 error) *MongoIndexView_CreateOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoIndexView_CreateOne_Call) RunAndReturn(run func(context.Context, mongo.IndexModel, ...*options.CreateIndexesOptions) (string, error)) *MongoIndexView_CreateOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoIndexView creates a new instance of MongoIndexView. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoIndexView(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoIndexView {
	mock := &MongoIndexView{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
