// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"

	repository "github.com/Mahno9/GoMicroservicesCourse/inventory/internal/repository"
)

// MongoCollection is an autogenerated mock type for the MongoCollection type
type MongoCollection struct {
	mock.Mock
}

type MongoCollection_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoCollection) EXPECT() *MongoCollection_Expecter {
	return &MongoCollection_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, filter, opts
func (_m *MongoCollection) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (repository.MongoCursor, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 repository.MongoCursor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) (repository.MongoCursor, error)); ok {
		return rf(ctx, filter, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) repository.MongoCursor); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.MongoCursor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoCollection_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MongoCollection_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOptions
func (_e *MongoCollection_Expecter) Find(ctx interface{}, filter interface{}, opts ...interface{}) *MongoCollection_Find_Call {
	return &MongoCollection_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MongoCollection_Find_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOptions)) *MongoCollection_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.FindOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.FindOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoCollection_Find_Call) Return(_a0 repository.MongoCursor, _a1 error) *MongoCollection_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoCollection_Find_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.FindOptions) (repository.MongoCursor, error)) *MongoCollection_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, filter, opts
func (_m *MongoCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) repository.MongoSingleResult {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 repository.MongoSingleResult
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOneOptions) repository.MongoSingleResult); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.MongoSingleResult)
		}
	}

	return r0
}

// MongoCollection_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MongoCollection_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOneOptions
func (_e *MongoCollection_Expecter) FindOne(ctx interface{}, filter interface{}, opts ...interface{}) *MongoCollection_FindOne_Call {
	return &MongoCollection_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MongoCollection_FindOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions)) *MongoCollection_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.FindOneOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.FindOneOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoCollection_FindOne_Call) Return(_a0 repository.MongoSingleResult) *MongoCollection_FindOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCollection_FindOne_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.FindOneOptions) repository.MongoSingleResult) *MongoCollection_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Indexes provides a mock function with no fields
func (_m *MongoCollection) Indexes() repository.MongoIndexView {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Indexes")
	}

	var r0 repository.MongoIndexView
	if rf, ok := ret.Get(0).(func() repository.MongoIndexView); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.MongoIndexView)
		}
	}

	return r0
}

// MongoCollection_Indexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indexes'
type MongoCollection_Indexes_Call struct {
	*mock.Call
}

// Indexes is a helper method to define mock.On call
func (_e *MongoCollection_Expecter) Indexes() *MongoCollection_Indexes_Call {
	return &MongoCollection_Indexes_Call{Call: _e.mock.On("Indexes")}
}

func (_c *MongoCollection_Indexes_Call) Run(run func()) *MongoCollection_Indexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoCollection_Indexes_Call) Return(_a0 repository.MongoIndexView) *MongoCollection_Indexes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoCollection_Indexes_Call) RunAndReturn(run func() repository.MongoIndexView) *MongoCollection_Indexes_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, documents, opts
func (_m *MongoCollection) InsertMany(ctx context.Context, documents []interface{}, opts ...*options.InsertManyOptions) (*mongo.InsertManyResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, documents)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 *mongo.InsertManyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []interface{}, ...*options.InsertManyOptions) (*mongo.InsertManyResult, error)); ok {
		return rf(ctx, documents, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []interface{}, ...*options.InsertManyOptions) *mongo.InsertManyResult); ok {
		r0 = rf(ctx, documents, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertManyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []interface{}, ...*options.InsertManyOptions) error); ok {
		r1 = rf(ctx, documents, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoCollection_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MongoCollection_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []interface{}
//   - opts ...*options.InsertManyOptions
func (_e *MongoCollection_Expecter) InsertMany(ctx interface{}, documents interface{}, opts ...interface{}) *MongoCollection_InsertMany_Call {
	return &MongoCollection_InsertMany_Call{Call: _e.mock.On("InsertMany",
		append([]interface{}{ctx, documents}, opts...)...)}
}

func (_c *MongoCollection_InsertMany_Call) Run(run func(ctx context.Context, documents []interface{}, opts ...*options.InsertManyOptions)) *MongoCollection_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.InsertManyOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.InsertManyOptions)
			}
		}
		run(args[0].(context.Context), args[1].([]interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoCollection_InsertMany_Call) Return(_a0 *mongo.InsertManyResult, _a1 error) *MongoCollection_InsertMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoCollection_InsertMany_Call) RunAndReturn(run func(context.Context, []interface{}, ...*options.InsertManyOptions) (*mongo.InsertManyResult, error)) *MongoCollection_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoCollection creates a new instance of MongoCollection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoCollection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoCollection {
	mock := &MongoCollection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
