with-expecter: true
# boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/Mahno9/GoMicroservicesCourse/inventory/internal:
    config:
      include-regex: "(.*Repository|Mongo.*)"
  github.com/Mahno9/GoMicroservicesCourse/order/internal:
    config:
      include-regex: ".*(Repository|Client|ProducerService)"
  github.com/Mahno9/GoMicroservicesCourse/assembly/internal:
    config:
      include-regex: ".*(Service)"
