// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClientsConfig is an autogenerated mock type for the ClientsConfig type
type ClientsConfig struct {
	mock.Mock
}

type ClientsConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientsConfig) EXPECT() *ClientsConfig_Expecter {
	return &ClientsConfig_Expecter{mock: &_m.Mock}
}

// InventoryAddress provides a mock function with no fields
func (_m *ClientsConfig) InventoryAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InventoryAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ClientsConfig_InventoryAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InventoryAddress'
type ClientsConfig_InventoryAddress_Call struct {
	*mock.Call
}

// InventoryAddress is a helper method to define mock.On call
func (_e *ClientsConfig_Expecter) InventoryAddress() *ClientsConfig_InventoryAddress_Call {
	return &ClientsConfig_InventoryAddress_Call{Call: _e.mock.On("InventoryAddress")}
}

func (_c *ClientsConfig_InventoryAddress_Call) Run(run func()) *ClientsConfig_InventoryAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientsConfig_InventoryAddress_Call) Return(_a0 string) *ClientsConfig_InventoryAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientsConfig_InventoryAddress_Call) RunAndReturn(run func() string) *ClientsConfig_InventoryAddress_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentAddress provides a mock function with no fields
func (_m *ClientsConfig) PaymentAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PaymentAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ClientsConfig_PaymentAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentAddress'
type ClientsConfig_PaymentAddress_Call struct {
	*mock.Call
}

// PaymentAddress is a helper method to define mock.On call
func (_e *ClientsConfig_Expecter) PaymentAddress() *ClientsConfig_PaymentAddress_Call {
	return &ClientsConfig_PaymentAddress_Call{Call: _e.mock.On("PaymentAddress")}
}

func (_c *ClientsConfig_PaymentAddress_Call) Run(run func()) *ClientsConfig_PaymentAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientsConfig_PaymentAddress_Call) Return(_a0 string) *ClientsConfig_PaymentAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientsConfig_PaymentAddress_Call) RunAndReturn(run func() string) *ClientsConfig_PaymentAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientsConfig creates a new instance of ClientsConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientsConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientsConfig {
	mock := &ClientsConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
