// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/Mahno9/GoMicroservicesCourse/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: order
func (_m *OrderRepository) Create(order *model.Order) (*model.Order, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Order) (*model.Order, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(*model.Order) *model.Order); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - order *model.Order
func (_e *OrderRepository_Expecter) Create(order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(order *model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(*model.Order) (*model.Order, error)) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: orderUuid
func (_m *OrderRepository) Get(orderUuid string) (*model.Order, error) {
	ret := _m.Called(orderUuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Order, error)); ok {
		return rf(orderUuid)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Order); ok {
		r0 = rf(orderUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - orderUuid string
func (_e *OrderRepository_Expecter) Get(orderUuid interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", orderUuid)}
}

func (_c *OrderRepository_Get_Call) Run(run func(orderUuid string)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(string) (*model.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: order
func (_m *OrderRepository) Update(order *model.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type OrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - order *model.Order
func (_e *OrderRepository_Expecter) Update(order interface{}) *OrderRepository_Update_Call {
	return &OrderRepository_Update_Call{Call: _e.mock.On("Update", order)}
}

func (_c *OrderRepository_Update_Call) Run(run func(order *model.Order)) *OrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_Update_Call) Return(_a0 error) *OrderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Update_Call) RunAndReturn(run func(*model.Order) error) *OrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
