// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type CreateOrderCreated struct {
	OrderUUID  OrderUUID  `json:"order_uuid"`
	TotalPrice TotalPrice `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderCreated) GetOrderUUID() OrderUUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderCreated) GetTotalPrice() TotalPrice {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderCreated) SetOrderUUID(val OrderUUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderCreated) SetTotalPrice(val TotalPrice) {
	s.TotalPrice = val
}

func (*CreateOrderCreated) createOrderRes() {}

type CreateOrderReq struct {
	UserUUID  UserUUID  `json:"user_uuid"`
	PartUuids PartUuids `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderReq) GetUserUUID() UserUUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderReq) GetPartUuids() PartUuids {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderReq) SetUserUUID(val UserUUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderReq) SetPartUuids(val PartUuids) {
	s.PartUuids = val
}

// Ref: #
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

type GetOrderOK struct {
	OrderUUID       OrderUUID       `json:"order_uuid"`
	UserUUID        UserUUID        `json:"user_uuid"`
	PartUuids       PartUuids       `json:"part_uuids"`
	TotalPrice      TotalPrice      `json:"total_price"`
	TransactionUUID TransactionUUID `json:"transaction_uuid"`
	PaymentMethod   PaymentMethod   `json:"payment_method"`
	Status          Status          `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderOK) GetOrderUUID() OrderUUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderOK) GetUserUUID() UserUUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderOK) GetPartUuids() PartUuids {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderOK) GetTotalPrice() TotalPrice {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderOK) GetTransactionUUID() TransactionUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderOK) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderOK) GetStatus() Status {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderOK) SetOrderUUID(val OrderUUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderOK) SetUserUUID(val UserUUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderOK) SetPartUuids(val PartUuids) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderOK) SetTotalPrice(val TotalPrice) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderOK) SetTransactionUUID(val TransactionUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderOK) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderOK) SetStatus(val Status) {
	s.Status = val
}

func (*GetOrderOK) getOrderRes() {}

// Ref: #
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) createOrderRes() {}
func (*NotFoundError) getOrderRes()    {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// OrderCancelConflict is response for OrderCancel operation.
type OrderCancelConflict struct{}

func (*OrderCancelConflict) orderCancelRes() {}

// OrderCancelNoContent is response for OrderCancel operation.
type OrderCancelNoContent struct{}

func (*OrderCancelNoContent) orderCancelRes() {}

// OrderCancelNotFound is response for OrderCancel operation.
type OrderCancelNotFound struct{}

func (*OrderCancelNotFound) orderCancelRes() {}

type OrderUUID string

type PartUuids []string

// PayOrderConflict is response for PayOrder operation.
type PayOrderConflict struct{}

func (*PayOrderConflict) payOrderRes() {}

type PayOrderOK struct {
	TransactionUUID TransactionUUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderOK) GetTransactionUUID() TransactionUUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderOK) SetTransactionUUID(val TransactionUUID) {
	s.TransactionUUID = val
}

func (*PayOrderOK) payOrderRes() {}

type PayOrderReq struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderReq) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderReq) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Способ оплаты.
// Ref: #
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Статус заказа.
// Ref: #
type Status string

const (
	StatusPENDINGPAYMENT Status = "PENDING_PAYMENT"
	StatusPAID           Status = "PAID"
	StatusCANCELLED      Status = "CANCELLED"
)

// AllValues returns all Status values.
func (Status) AllValues() []Status {
	return []Status{
		StatusPENDINGPAYMENT,
		StatusPAID,
		StatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Status) MarshalText() ([]byte, error) {
	switch s {
	case StatusPENDINGPAYMENT:
		return []byte(s), nil
	case StatusPAID:
		return []byte(s), nil
	case StatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Status) UnmarshalText(data []byte) error {
	switch Status(data) {
	case StatusPENDINGPAYMENT:
		*s = StatusPENDINGPAYMENT
		return nil
	case StatusPAID:
		*s = StatusPAID
		return nil
	case StatusCANCELLED:
		*s = StatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TotalPrice float64

type TransactionUUID string

type UserUUID string
