// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateOrder implements CreateOrder operation.
//
// Создать новый заказ для деталей корабля.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderReq) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements GetOrder operation.
//
// Получить заказ по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCancel implements OrderCancel operation.
//
// Отмена заказа.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Оплата собранного заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderReq, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
